version: '3.8'
services:
  fastapi:
    image: "fastapi:latest"
    ports:
      - "8000:8000"

  streamlit:
    image: "streamlit:latest"
    ports:
      - "8501:8501"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
volumes:
  db_data:
