services:
  fastapi:
    build:
      context: ./backend/fastapi
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
  streamlit:
    build:
      context: ./app/streamlit
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501"
  db:
    build:
      context: ./backend/postgres
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
volumes:
  db_data:
